
### 文字
POST http://localhost:8080/v1/chat/completions
Content-Type: application/json

{
  "model": "gpt-3.5-turbo-1106",
  "stream": true,
  "messages": [
    {
      "role": "user",
      "content": "who are you"
    }
  ]
}

### 图片
POST http://localhost:8080/v1/images/generations
Content-Type: application/json

{
  "prompt": "小猫",
  "n": 1,
  "size": "256x256"
}

### 音频1 Speech to Text
POST http://localhost:8080/v1/audio/transcriptions
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="model"
Content-Type: text/plain

whisper-1

--WebAppBoundary
Content-Disposition: form-data; name="temperature"
Content-Type: text/plain

0

--WebAppBoundary
Content-Disposition: form-data; name="response_format"
Content-Type: text/plain

text

--WebAppBoundary
Content-Disposition: form-data; name="language"
Content-Type: text/plain

zh

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="dictvoice.mp3"
Content-Type: text/plain

< dictvoice.mp3
--WebAppBoundary--


### 音频2 Text to Speech
POST http://localhost:8080/v1/audio/speech
Content-Type: application/json

{
  "model": "tts-1",
  "voice": "alloy",
  "input": "Today is a wonderful day to build something people love!"
}