### 短链生成
POST {{host}}/u
Content-Type: application/json

"123"

### 短链跳转
GET {{host}}/u/1d2480


### 文字
POST {{host}}/v1/chat/completions
Content-Type: application/json
Authorization: Bearer

{
  "model": "gpt-3.5-turbo-1106",
  "stream": true,
  "messages": [
    {
      "role": "user",
      "content": "who are you"
    }
  ]
}

### 图片
POST {{host}}/v1/images/generations
Content-Type: application/json

{
  "prompt": "小狗",
  "n": 1,
  "size": "256x256"
}

###  音频1 Speech to Text
POST {{host}}/v1/audio/transcriptions
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="model"
Content-Type: text/plain

whisper-1

--WebAppBoundary
Content-Disposition: form-data; name="temperature"
Content-Type: text/plain

0

--WebAppBoundary
Content-Disposition: form-data; name="response_format"
Content-Type: text/plain

text

--WebAppBoundary
Content-Disposition: form-data; name="language"
Content-Type: text/plain

zh

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="dictvoice.mp3"
Content-Type: text/plain

< dictvoice.mp3
--WebAppBoundary--


### 音频2 Text to Speech
POST {{host}}/v1/audio/speech
Content-Type: application/json

{
  "model": "tts-1",
  "voice": "alloy",
  "input": "Unless required by applicable law or agreed to in writing, software"
}


###
POST {{host}}/v1/models/gemini-pro:generateContent
Content-Type: application/json

{
  "contents": [
    {
      "role": "user",
      "parts": [
        {
          "text": "who are you"
        }
      ]
    }
  ]
}

<> 2024-05-23T180637.200.json

###
POST {{host}}/v1/models/gemini-pro:streamGenerateContent
Content-Type: application/json

{
  "contents": [
    {
      "role": "model",
      "parts": [
        {
          "text": "我是openai"
        }
      ]
    },
    {
      "role": "user",
      "parts": [
        {
          "text": "who are you"
        }
      ]
    }
  ]
}

###
POST {{host}}/v1beta/models/gemini-1.5-flash:generateContent?key=$GOOGLE_API_KEY
Content-Type: application/json

{
  "generationConfig": {
    "temperature": 0.6,
    "topP": 1
  },
  "safetySettings": [
    {
      "category": "HARM_CATEGORY_HATE_SPEECH",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_HARASSMENT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
      "threshold": "BLOCK_NONE"
    }
  ],
  "contents": [
    {
      "parts": [
        {
          "text": "我输入一个内容，因为我对此一无所知，需要快速学习，列举出学习路线"
        }
      ],
      "role": "user"
    },
    {
      "parts": [
        {
          "text": ""
        }
      ],
      "role": "model"
    },
    {
      "parts": [
        {
          "text": "人工智能"
        }
      ],
      "role": "user"
    }
  ]
}

###
POST {{host}}/v1beta/models/gemini-1.5-pro-latest:generateContent?alt=sse&key=AIzaSyB6WE3gEeaGIT1SMOuFeU_k1_d7TPa7Bsw
Content-Type: application/json

{
  "generationConfig": {
    "temperature": 0.6,
    "topP": 1
  },
  "safetySettings": [
    {
      "category": "HARM_CATEGORY_HATE_SPEECH",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_HARASSMENT",
      "threshold": "BLOCK_NONE"
    },
    {
      "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
      "threshold": "BLOCK_NONE"
    }
  ],
  "contents": [
    {
      "parts": [
        {
          "text": "我输入一个内容，因为我对此一无所知，需要快速学习，列举出学习路线"
        }
      ],
      "role": "user"
    },
    {
      "parts": [
        {
          "text": ""
        }
      ],
      "role": "model"
    },
    {
      "parts": [
        {
          "text": "人工智能"
        }
      ],
      "role": "user"
    }
  ]
}
